---
vm:
    box: bento/ubuntu-16.04
    memory: '1024'
    cpus: '1'

network:
    hostname: 'FQDN'
    private_network: 192.168.7.7
    aliases:
      - 'ALIAS1'
      #- 'ALIAS2'
project:
    folder: /var/www
puppet:
    options: '--verbose --debug'
    includes:
      - add_php
      - add_apache
      - add_mariadb
      - add_vendor
      - add_migrations
      - add_ohmyzsh
      - add_nodejs
      - add_mailhog
      - add_motd
    add_php:
      version: '7.3'
    add_apache:
      docroot: /var/www/public
    add_mariadb:
      username: vagrant
      password: vagrant
      databases:
#        DBNAME1:
#          ensure: 'present'
#          charset: 'utf8'
#        DBNAME2:
#          ensure: 'present'
#          charset: 'utf8'